#! /bin/bash

source "buildutils.sh"

# PACKAGE ####################################################################

PACKAGE=LXML
DEPENDENCIES="Python Zlib"

# SETUP ######################################################################

set -e
cd `dirname "$0"`
PREFIX=`pwd`

if [ -e ".${PACKAGE}-BUILT" ]; then
    exit 0
fi

# DEPENDENCIES ###############################################################

build_deps $DEPENDENCIES

# BUILD STEPS ###############################################################

echo "Installing ${PACKAGE} ..."
PATH=${PREFIX}/bin:$PATH
easy_install lxml

##############################################################################

cd "${PREFIX}"
touch ".${PACKAGE}-BUILT"

##############################################################################
